# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON d:\WORKSPACE_WIN\SUSTech_CS301_Project\CMAKE

function(add_lvgl_target_properties TARGET_NAME)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lv_driver>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl/src>"

    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lv_driver>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl/src>"

    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lv_driver>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl/src>"

    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lv_driver>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core/Src/lvgl/src>"

    )



file(GLOB_RECURSE LV_DRIVER "Core/Src/lv_driver/*.c")
file(GLOB_RECURSE LV_CORE "$Core/Src/lvgl/src/lv_core/*.c")
file(GLOB_RECURSE LV_DRAW "Core/Src/lvgl/src/lv_draw/*.c")
file(GLOB_RECURSE LV_FONT "Core/Src/lvgl/src/lv_font/*.c")
file(GLOB_RECURSE LV_HAL "Core/Src/lvgl/src/lv_hal/*.c")
file(GLOB_RECURSE LV_MISC "Core/Src/lvgl/src/lv_misc/*.c")
file(GLOB_RECURSE LV_THEMES "Core/Src/lvgl/src/lv_themes/*.c")
file(GLOB_RECURSE LV_WIDGETS "Core/Src/lvgl/src/lv_widgets/*.c")

target_sources(
    ${TARGET_NAME} PRIVATE
    ${LV_DRIVER}
    ${LVCORE}
    ${LV_DRAW}
    ${LV_FONT}
    ${LV_HAL}
    ${LV_MISC}
    ${LV_THEMES}
    ${LV_WIDGETS}
)



endfunction()