# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON d:\WORKSPACE_WIN\SUSTech_CS301_Project\CMAKE

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32F103xE>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:STM32F103xE>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32F103xE>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:STM32F103xE>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F1xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F1xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F1xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F1xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m3>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m3>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m3>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m3>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32F103RCTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32F103RCTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core\\Src\\lvgl\\src\\lv_core\\lv_disp.c"
    "Core\\Src\\lvgl\\src\\lv_core\\lv_group.c"
    "Core\\Src\\lvgl\\src\\lv_core\\lv_indev.c"
    "Core\\Src\\lvgl\\src\\lv_core\\lv_obj.c"
    "Core\\Src\\lvgl\\src\\lv_core\\lv_refr.c"
    "Core\\Src\\lvgl\\src\\lv_core\\lv_style.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_arc.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_blend.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_img.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_label.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_line.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_mask.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_rect.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_draw_triangle.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_img_buf.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_img_cache.c"
    "Core\\Src\\lvgl\\src\\lv_draw\\lv_img_decoder.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_dejavu_16_persian_hebrew.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_fmt_txt.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_loader.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_10.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_12_subpx.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_12.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_14.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_16.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_18.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_20.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_22.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_24.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_26.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_28_compressed.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_28.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_30.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_32.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_34.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_36.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_38.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_40.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_42.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_44.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_46.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_48.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_montserrat_8.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_simsun_16_cjk.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_unscii_16.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font_unscii_8.c"
    "Core\\Src\\lvgl\\src\\lv_font\\lv_font.c"
    "Core\\Src\\lvgl\\src\\lv_gpu\\lv_gpu_nxp_pxp_osa.c"
    "Core\\Src\\lvgl\\src\\lv_gpu\\lv_gpu_nxp_pxp.c"
    "Core\\Src\\lvgl\\src\\lv_gpu\\lv_gpu_nxp_vglite.c"
    "Core\\Src\\lvgl\\src\\lv_gpu\\lv_gpu_stm32_dma2d.c"
    "Core\\Src\\lvgl\\src\\lv_hal\\lv_hal_disp.c"
    "Core\\Src\\lvgl\\src\\lv_hal\\lv_hal_indev.c"
    "Core\\Src\\lvgl\\src\\lv_hal\\lv_hal_tick.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_anim.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_area.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_async.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_bidi.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_color.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_debug.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_fs.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_gc.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_ll.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_log.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_math.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_mem.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_printf.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_task.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_templ.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_txt_ap.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_txt.c"
    "Core\\Src\\lvgl\\src\\lv_misc\\lv_utils.c"
    "Core\\Src\\lvgl\\src\\lv_themes\\lv_theme_empty.c"
    "Core\\Src\\lvgl\\src\\lv_themes\\lv_theme_material.c"
    "Core\\Src\\lvgl\\src\\lv_themes\\lv_theme_mono.c"
    "Core\\Src\\lvgl\\src\\lv_themes\\lv_theme_template.c"
    "Core\\Src\\lvgl\\src\\lv_themes\\lv_theme.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_arc.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_bar.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_btn.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_btnmatrix.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_calendar.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_canvas.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_chart.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_checkbox.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_cont.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_cpicker.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_dropdown.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_gauge.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_img.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_imgbtn.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_keyboard.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_label.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_led.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_line.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_linemeter.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_list.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_msgbox.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_objmask.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_objx_templ.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_page.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_roller.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_slider.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_spinbox.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_spinner.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_switch.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_table.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_tabview.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_textarea.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_tileview.c"
    "Core\\Src\\lvgl\\src\\lv_widgets\\lv_win.c"
    "Core\\Src\\config.c"
    "Core\\Src\\frameworks\\framework.cpp"
    "Core\\Src\\frameworks\\scene.cpp"
    "Core\\Src\\image_source.cpp"
    "Core\\Src\\lib\\24cxx.c"
    "Core\\Src\\lib\\delay.c"
    "Core\\Src\\lib\\lcd.c"
    "Core\\Src\\lib\\led.cpp"
    "Core\\Src\\lib\\myiic.c"
    "Core\\Src\\lib\\touch.c"
    
    "Core\\Src\\lv_driver\\lv_port_disp.c"
    "Core\\Src\\lv_driver\\lv_port_indev.c"
    # "Core\\Src\\main.c"
    "Core\\Src\\main.cpp"
    "Core\\Src\\stm32f1xx_hal_msp.c"
    # "Core\\Src\\stm32f1xx_it.c"
    "Core\\Src\\stm32f1xx_it.cpp"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32f1xx.c"
    "Core\\Startup\\startup_stm32f103rctx.s"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_cortex.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_dma.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_exti.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_flash_ex.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_flash.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_gpio_ex.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_gpio.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_i2c.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_pwr.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_rcc_ex.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_rcc.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_tim_ex.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_tim.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal_uart.c"
    "Drivers\\STM32F1xx_HAL_Driver\\Src\\stm32f1xx_hal.c"

)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()